Repository ITSM-Project/SLASH-FE, pull requests merged in 2024-11, with the labels that each got.

#34 [REFACTOR]: 업무 요청 화면 요청 정보, 요청 내용 컴포넌트 분리
  src/components/common/CheckBox.js
  src/components/feature/request/CreateRequest.js
  src/components/feature/request/CreateRequestForm.css
  src/components/feature/request/CreateRequestForm.js
  src/components/feature/request/RequestContentForm.css
  src/components/feature/request/RequestContentForm.js
  src/components/feature/request/RequestDropdown.css
  src/components/feature/request/RequestDropdown.js
  src/components/feature/request/RequestInfoForm.css
  src/components/feature/request/RequestInfoForm.js
  src/service/api/userService.js
  src/styles/CheckBox.css
Labels: ♻️REFACTOR, 💄STYLE

#39 [FEAT] 로그인 페이지 구현
  src/pages/login/ErrorMessage.js
  src/pages/login/Header.js
  src/pages/login/InputGroup.js
  src/pages/login/Login.css
  src/pages/login/Login.js
Labels: ✨FEAT, 🔧FIX, 💄STYLE

#43 [FEAT]: 요청 상세보기 모달창 화면 구현
  .idea/.gitignore
  .idea/SLASH-FE.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/feature/request/RequestContentForm.css
  src/components/feature/request/RequestContentForm.js
  src/components/feature/request/RequestModal.css
  src/components/feature/request/create/CreateRequest.js
  src/components/feature/request/create/CreateRequestForm.js
  src/components/feature/request/create/CreateRequestInfoForm.css
  src/components/feature/request/create/CreateRequestInfoForm.js
  src/components/feature/request/select/RequestDetail.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailInfoForm.js
  src/components/feature/request/select/RequestDetailModal.js
  src/components/labels/request/DueOneTimeLabel.js
  src/components/labels/request/RequestLabel.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/service/api/userService.js
  src/styles/Label.css
Labels: ✨FEAT, 💄STYLE

#56 [FEAT]: 요청 수정, 삭제 기능 구현
  src/components/feature/request/EditRequestForm.js
  src/components/feature/request/select/RequestDetail.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailInfoForm.js
  src/components/feature/request/select/RequestDetailModal.js
  src/service/api/userService.js
Labels: ✨FEAT, 💄STYLE

#62 🐛 FIX: axios 경로 수정
  package-lock.json
  package.json
  src/components/layout/content/contractManager/ContractManagerMainContent.js
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
Labels: 🔧FIX

#64 [FEAT]: 로그인 화면 redirection 및 JWT 토큰
  package-lock.json
  package.json
  src/pages/login/ErrorMessage.js
  src/pages/login/Header.js
  src/pages/login/InputGroup.js
  src/pages/login/Login.css
  src/pages/login/Login.js
Labels: ✨FEAT, 🔧FIX

#66 [FEAT]: 매니저 할당 및 할당 완료 컴포넌트 구현
  package-lock.json
  package.json
  src/api/UserService.js
  src/components/common/button/AssignmentButton.js
  src/components/feature/modal/Modal.css
  src/components/feature/modal/Modal.js
  src/components/layout/content/contractManager/RequestDetailContent.js
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMainTop/ContractManagerMainTop.css
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.css
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
  src/pages/contractManager/ContractManagerMain.js
  src/pages/contractManager/RequestDetail.js
  src/pages/login/Login.js
  src/shared/Router.js
Labels: ✨FEAT

#65 [Feat]: 유저의 요청 관리 표와 요청 내역 모달 연결
  package-lock.json
  package.json
  src/components/dropdown/Dropdown.css
  src/components/dropdown/Dropdown.js
  src/components/labels/request/RequestLabel.js
  src/components/layout/content/requestManager/RequestManagerMainContent.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/UserMainContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/TableView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/TableView.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/styles/Content.css
Labels: ✨FEAT

#72 [FIX]: 백통신 API 수정
  src/api/UserService.js
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/service/api/userService.js
Labels: 🔧FIX

#74 [FEAT]: 사이드바 이동 페이지 설정
  src/components/layout/content/contractManager/contract/contractContent/ContractStep2
  src/components/layout/content/contractManager/contract/contractForm/ContractListForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractListForm.js
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/pages/login/Login.css
Labels: ✨FEAT, ♻️REFACTOR

#75 [FIX]: 요청 등록 모달창 오류 수정
  src/components/feature/modal/Modal.css
  src/components/feature/modal/Modal.js
  src/components/feature/request/RequestModal.css
  src/components/feature/request/create/CreateRequestForm.js
  src/components/feature/request/select/RequestDetail.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailModal.js
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/service/api/userService.js
Labels: 🔧FIX, ♻️REFACTOR

#78 [REFACTOR]: 업무 할당하기 api변경
  src/api/UserService.js
Labels: 🔧FIX, ♻️REFACTOR

#79 [FEAT]: 할당하기 페이지에 요청 상세보기 컴포넌트 추가
  src/components/labels/request/DueOneTimeLabel.js
  src/components/labels/request/RequestLabel.js
  src/components/layout/content/contractManager/RequestDetailContent.js
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
Labels: ✨FEAT

#81 [FIX]: 각종 오류 수정
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
Labels: 🔧FIX

#88 [FIX]: 멘토링 이후 수정 및 추가 사항
  .gitignore
  package-lock.json
  package.json
  src/api/UserService.js
  src/components/common/button/AssignmentButton.js
  src/components/dropdown/Dropdown.css
  src/components/labels/equipmentType/EquipmentTypeLabel.js
  src/components/labels/processStatus/ProcessStatusLabel.js
  src/components/labels/request/RequestLabel.js
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/UserMainContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/shared/Router.js
  src/styles/RequestManageBottom.css
  src/styles/Sidebar.css
Labels: ✨FEAT, 🔧FIX, ♻️REFACTOR, 🔥REMOVE, 💄STYLE

#84 [FIX]: 요청 관련 url 수정, 로그인 성공 응답 구조 수정
  src/pages/login/Login.js
  src/service/api/userService.js
Labels: 🔧FIX

#86 [REFACTOR]: 요청매니저 메인 코드 리팩토링
  src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.js
Labels: ♻️REFACTOR

#89 [REFACTOR]: 요청 생성 시 계약 아이디 넘겨주도록 수정
  src/components/feature/request/create/CreateRequest.js
  src/service/api/userService.js
Labels: ✨FEAT, ♻️REFACTOR

#91 [REFACTOR]: 계약 생성 및 조회 화면 UI 변경
  src/components/feature/table/ContractListTable.js
  src/components/feature/table/GradeInputTable.js
  src/components/feature/table/NoScoreGradeInputTable.js
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.js
  src/styles/Common.css
Labels: ♻️REFACTOR, 🔥REMOVE

#94 [REFACTOR]: 할당하기 버튼 추가 및 로컬스토리지에 유저아이디 추가
  src/api/UserService.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailInfoForm.js
Labels: ✨FEAT

#102 [FEAT]: 상단바 2가지 버전으로 구현
  src/components/common/header/ContractHeader.css
  src/components/common/header/ContractHeaderV1.js
  src/components/common/header/ContractHeaderV2.js
Labels: ✨FEAT

#96 [REFACTOR]: 계약매니저 메인페이지 UI 변경
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/api/UserService.js
  src/components/feature/table/ContractListTable.js
  src/components/feature/table/EvaluationItemList.css
  src/components/feature/table/EvaluationItemListTable.js
  src/components/layout/content/contractManager/ContractManagerMainContent.js
  src/components/layout/content/contractManager/contract/ContractInfo.js
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.js
  src/components/layout/content/contractManager/contract/contractForm/ContractInfoForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractInfoForm.js
  src/components/layout/content/contractManager/contract/contractForm/ContractListForm.js
  src/components/layout/content/contractManager/contract/contractForm/UpdateContractForm.js
  src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.css
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.js
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMainTop/ContractManagerMainTop.css
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMainTop/ContractManagerMainTop.js
  src/pages/contractManager/ContractInformation.js
  src/shared/Router.js
Labels: ✨FEAT, ♻️REFACTOR, 🔥REMOVE, 💄STYLE

#108 [FEAT]: logout 버튼 기능 구현 및 login 리팩토링
  src/api/AuthService.js
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/api/Interceptor.js
  src/api/UserService.js
  src/components/common/ProtectedRoute.js
  src/components/common/button/LogoutButton.js
  src/components/layout/content/login/LoginErrorMessage.js
  src/components/layout/content/login/LoginInputGroup.js
  src/components/layout/content/login/LoginMain.js
  src/components/layout/content/login/LoginTitle.js
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/hooks/useLogin.js
  src/pages/login/ErrorMessage.js
  src/pages/login/Header.js
  src/pages/login/Login.js
  src/pages/login/LoginPage.js
  src/shared/Router.js
  src/styles/Login.css
Labels: ✨FEAT, ♻️REFACTOR

#110 [FEAT] : 종합 지표 조회 화면 구현 및 api 연결
  src/api/CommonService.js
  src/api/UserService.js
  src/components/common/header/ContractHeader.css
  src/components/common/header/ContractHeaderV1.js
  src/components/common/header/ContractHeaderV2.js
  src/components/layout/content/contractManager/indexManagment/DetailIndexContent.js
  src/components/layout/content/contractManager/indexManagment/EvaluationDetailTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/detailIndex/DetailIndexContent.js
  src/components/layout/content/user/detailIndex/EvaluationDetailTable.js
  src/components/layout/content/user/indexManagement/BottomTable.css
  src/components/layout/content/user/indexManagement/BottomTable.js
  src/components/layout/content/user/indexManagement/IndexManagementContent.js
  src/components/layout/content/user/indexManagement/MiddleIndex.css
  src/components/layout/content/user/indexManagement/MiddleIndex.js
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/pages/user/DetailIndex.js
  src/pages/user/IndexManagement.js
  src/shared/Router.js
  src/styles/CommonTable.css
  src/styles/Font.css
  src/styles/Sidebar.css
Labels: ✨FEAT, 💄STYLE

#113 [FIX]: merge 후 오류 해결
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/components/dropdown/Dropdown.css
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.css
  src/components/layout/content/user/detailIndex/EvaluationDetailTable.js
  src/components/layout/content/user/indexManagement/BottomTable.css
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/styles/CommonTable.css
Labels: 🔧FIX, 💄STYLE

#111 [FEAT]: 자동계산 날짜별 필터링 및 카테고리별 측정
  src/api/ContractManagerService.js
  src/api/RequestManagerService.js
  src/api/UserService.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/layout/content/contractManager/IndicatorCalculatorContent.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
  src/components/layout/content/requestManager/RequestManagerStatusContent.js
  src/components/layout/content/requestManager/requestManagerStatus/RequestStatus.js
  src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/pages/contractManager/IndicatorCalculator.js
  src/pages/requestManager/RequestManagerStatus.js
  src/shared/Router.js
Labels: ✨FEAT, ♻️REFACTOR, 💄STYLE

#115 🐛 FIX: 오류 수정
  src/shared/Router.js
Labels: 🔧FIX

#119 [FEAT]: 사이드 바 연결
  src/components/dropdown/Dropdown.css
  src/components/layout/content/requestManager/RequestManagerStatusContent.js
  src/components/layout/content/requestManager/requestManagerStatus/RequestStatus.js
  src/components/layout/content/user/UserMainContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/shared/Router.js
Labels: ♻️REFACTOR

#121 [FEAT]: 통계 측정 결과 자세히 보기 css 수정, 요청 관리자 메인
  src/components/feature/chart/systemTypeChart/PieChart.css
  src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.css
  src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.css
  src/styles/CommonTable.css
  src/styles/RequestManageBottom.css
Labels: 💄STYLE

#124 [FEAT]: 유저 메인 css 수정
  src/components/dropdown/Dropdown.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css
  src/styles/RequestManageBottom.css
Labels: 💄STYLE

#134 [FEAT]: 자동계산 페이지 삭제 버튼 및 api연결
  src/api/ContractManagerService.js
  src/components/feature/table/EvaluationItemList.css
  src/components/feature/table/IndicatorTable.css
  src/components/feature/table/IndicatorTable.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js
Labels: ✨FEAT

#135 [FIX]: 요청 오류 수정
  src/components/feature/request/create/CreateRequest.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
Labels: 🔧FIX

#138 [REFACTOR]: 유저 통계 조회 페이지 오류 수정
  src/api/CommonService.js
  src/components/common/header/UserHeaderV1.js
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.css
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.js
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/UpdateEvaluationItemInfoForm.js
  src/components/layout/content/user/UserMainContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
Labels: ♻️REFACTOR, 💄STYLE

#140 [FEAT]: 계약관리자 지표 관리 자세히 보기 페이지 구현
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEditContent.js
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/pages/contractManager/EstimateIndicatorEdit.js
  src/shared/Router.js
Labels: 🔧FIX

#142 [FEAT] : 권한별 사이드 바 오류 수정 및 탭 지정
  src/components/layout/content/contractManager/statisticsResults/BottomTable.css
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.js
  src/components/layout/content/contractManager/statisticsResults/MiddleIndex.css
  src/components/layout/content/contractManager/statisticsResults/MiddleIndex.js
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/RequestManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/pages/contractManager/StatisticsResults.js
  src/shared/Router.js
  src/styles/Sidebar.css
Labels: ✨FEAT, 🔧FIX, 💄STYLE

#145 [FEAT]: 시스템별, 장비별, 날짜별 차트 필터링 및 css
  src/api/CommonService.js
  src/api/UserService.js
  src/components/common/header/ContractHeader.css
  src/components/dropdown/DropDownHeader.js
  src/components/dropdown/Dropdown.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
Labels: ✨FEAT, 🔧FIX, ♻️REFACTOR

#149 [FEAT]: 서비스 요청 적기 처리율 테이블 값 안나오는 오류 해결 및 초기날짜 현재날짜로 수정
  src/components/common/header/UserHeaderV1.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
Labels: 🔧FIX, ♻️REFACTOR, 💄STYLE

#150 [FEAT]: 할당하기 및 요청 처리 완료 오류 수정
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailInfoForm.js
  src/components/labels/request/DueOneTimeLabel.js
  src/components/layout/content/contractManager/requestAllocation/RequestAllocationTable.js
  src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.js
  src/shared/Router.js
Labels: ✨FEAT, 🔧FIX, 💄STYLE

#156 [FEAT]: 연도 필터 헤더 컴포넌트 구현
  package-lock.json
  package.json
  src/components/common/header/YearHeader.css
  src/components/common/header/YearHeader.js
Labels: ✨FEAT

#157 [FEAT]: 유저 요청 관리 상단 백 ,헤더 연결
  src/api/CommonService.js
  src/api/UserService.js
  src/components/common/header/ContractHeaderV3.js
  src/components/layout/content/user/requestManagement/RequestManagementContent.js
  src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.css
  src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.js
Labels: ✨FEAT, ♻️REFACTOR

#158 [FEAT]: 연간 차트 화면 구현 + 백 연결
  src/api/CommonService.js
  src/components/common/header/YearHeader.js
  src/components/feature/chart/yearIndicatorChart/YearIndicatorChart.js
  src/components/layout/content/contractManager/statisticsResults/BottomTable.css
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicator.css
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorForm.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorInfo.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorTable.js
  src/components/layout/content/user/indexManagement/BottomTable.css
  src/components/layout/sidebar/ContactManagerSidebar.js
  src/components/layout/sidebar/UserSidebar.js
  src/pages/contractManager/YearIndicator.js
  src/shared/Router.js
Labels: ✨FEAT, 💄STYLE

#162 [FEAT]: 차트 색상 변경
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
Labels: ♻️REFACTOR, 💄STYLE

#164 [FIX]: 장애 적기 처리율 오류, 요청 수정 오류
  src/components/feature/request/EditRequestForm.js
  src/components/feature/request/RequestContentForm.css
  src/components/feature/request/select/RequestDetailForm.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
Labels: 🔧FIX

#165 [REFACTO]: 지표 관리 페이지헤더 변경
  src/api/UserService.js
  src/components/feature/table/ StatisticsListTable.js
  src/components/layout/content/contractManager/contract/contractForm/ContractListForm.css
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/indexManagement/BottomTable.js
  src/pages/contractManager/StatisticsPdf.js
  src/shared/Router.js
Labels: ♻️REFACTOR, 💄STYLE

#168 [REFACTOR]: 지표관리 데이터 칼럼 변경 및 삭제 수정
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/components/feature/table/IndicatorTable.js
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/pages/user/UserYearIndicator.js
  src/shared/Router.js
Labels: ♻️REFACTOR, 🔥REMOVE

#171 [FIX]: 요청 관리 표 권한 별로 수정된 API에 따라 수정 & 종합지표 수정할 수 있도록 기능 구현
  src/api/UserService.js
  src/components/feature/table/IndicatorTable.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js
  src/components/layout/content/contractManager/requestAllocation/RequestAllocationContent.js
  src/components/layout/content/contractManager/requestAllocation/RequestAllocationTable.js
  src/components/layout/content/requestManager/RequestManagerMainContent.js
  src/components/layout/content/requestManager/RequestManagerStatusContent.js
  src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementContent.js
Labels: ✨FEAT, 🔧FIX

#173 [REFACTOR]: 계약매니저 페이지 전반 상태관리 변경 리팩토링
  src/App.js
  src/api/AuthService.js
  src/api/CommonService.js
  src/api/ContractManagerService.js
  src/api/Interceptor.js
  src/api/RequestManagerService.js
  src/api/UserService.js
  src/components/common/ProtectedRoute.js
  src/components/common/button/LogoutButton.js
  src/components/common/header/ContentsHeader.js
  src/components/common/header/ContractHeader.css
  src/components/feature/chart/GradeChart.js
  src/components/feature/table/ StatisticsListTable.js
  src/components/feature/table/EvaluationItemListTable.js
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.js
  src/components/layout/content/contractManager/contract/contractForm/ContractListForm.js
  src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.js
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/AddEvaluationItemForm.css
  src/components/layout/content/contractManager/statisticsResults/BottomTable.js
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.css
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.js
  src/components/layout/content/contractManager/statisticsResults/MiddleIndex.css
  src/components/layout/content/contractManager/statisticsResults/MiddleIndex.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorForm.js
  src/components/layout/content/user/indexManagement/BottomTable.js
  src/components/layout/content/user/indexManagement/IndexManagementContent.js
  src/components/layout/content/user/indexManagement/MiddleIndex.css
  src/components/layout/content/user/indexManagement/MiddleIndex.js
  src/context/AuthContext.js
  src/pages/contractManager/ContractList.js
  src/pages/login/LoginPage.js
  src/pages/user/IndexManagement.js
  src/pages/user/UserYearIndicator.js
  src/shared/Router.js
Labels: ✨FEAT, 🔧FIX, ♻️REFACTOR, 🔥REMOVE, 💄STYLE

#178 [Fix]: 각종 오류 수정
  src/api/ContractManagerService.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/table/IndicatorTable.css
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/UpdateEvaluationItemInfoForm.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/service/api/userService.js
Labels: 🔧FIX

#182 [FIX]: 유저 메인 데이터 리로드 오류 및 예외처리
  src/components/common/header/ContentsHeader.js
  src/components/common/header/ContractHeader.css
  src/components/common/header/YearHeader.css
  src/components/common/header/YearHeader.js
  src/components/feature/request/RequestModal.css
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.js
  src/components/feature/table/GradeInputTable.js
  src/components/feature/table/NoScoreGradeInputTable.js
  src/components/feature/table/ServiceDetailInputTable.js
  src/components/feature/table/TaskDetailInputTable.js
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.css
  src/components/layout/content/contractManager/contract/contractForm/ContractForm.js
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.css
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.js
  src/components/layout/content/contractManager/yearIndicator/YearIndicatorForm.js
  src/components/layout/content/user/UserMainContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
  src/components/layout/content/user/requestManagement/RequestManagementContent.js
  src/shared/Router.js
Labels: 🔧FIX, ♻️REFACTOR, 🔥REMOVE, 💄STYLE

#185 [REFACTOR]: 자동계산 칼럼삭제 및 유저메인 불필요 칼럼 삭제
  src/api/ContractManagerService.js
  src/components/common/header/ContentsHeader.js
  src/components/common/header/ContractHeaderV1.js
  src/components/common/header/ContractHeaderV3.js
  src/components/common/header/UserHeaderV1.js
  src/components/feature/table/ StatisticsListTable.js
  src/components/feature/table/EvaluationItemList.css
  src/components/feature/table/EvaluationItemListTable.js
  src/components/feature/table/IndicatorTable.js
  src/components/feature/table/ServiceDetailInputTable.js
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/AddEvaluationItemForm.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js
  src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js
  src/components/layout/content/contractManager/requestAllocation/RequestAllocationContent.js
  src/components/layout/content/contractManager/statisticsResults/IndexManagementContent.js
  src/components/layout/content/requestManager/RequestManagerStatusContent.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
  src/components/layout/content/user/dashBoard/dashBoardBottom/TableView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/TableView.js
Labels: ✨FEAT, 🔧FIX, ♻️REFACTOR, 🔥REMOVE

#186 [FIX]: 계약 아이디 넘기도록 수정
  src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
Labels: 🔧FIX

#193 [STYLE]: 유저 메인 차트 CSS 수정
  package-lock.json
  package.json
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css
  src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js
  src/styles/RequestManageBottom.css
Labels: 💄STYLE

#192 REFACTOR: 요청타입 테이블 수정
  src/components/feature/request/RequestModal.css
  src/components/feature/request/select/RequestDetail.js
  src/components/feature/request/select/RequestDetailForm.js
  src/components/feature/request/select/RequestDetailInfoForm.css
  src/components/feature/request/select/RequestDetailInfoForm.js
  src/components/feature/table/ServiceDetailInputTable.js
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/AddEvaluationItemForm.js
  src/components/layout/content/contractManager/evaluationItem/evaluationItemForm/UpdateEvaluationItemInfoForm.js
Labels: ♻️REFACTOR
